name: web_dashboard
description: A dashboard app sample
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  charts_flutter: ^0.10.0
  cloud_firestore: ^2.1.0
  cupertino_icons: ^1.0.3
  dropdown_search: ^0.6.1           #https://pub.dev/packages/dropdown_search
  
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  fl_chart: ^0.36.1                 #https://pub.dev/packages/fl_chart
  
  flutter:
    sdk: flutter
  
  flutter_datetime_picker: ^1.5.1   #https://pub.dev/packages/flutter_datetime_picker
  flutter_multi_formatter: ^2.1.0   #https://pub.dev/packages/flutter_multi_formatter
  flutter_svg: ^0.22.0              #https://pub.dev/packages/flutter_svg
  get: ^4.1.4                       #https://pub.dev/packages/get
  get_storage: ^2.0.2               #https://pub.dev/packages/get_storage
  google_fonts: ^2.1.0              #https://pub.dev/packages/google_fonts
  google_sign_in: ^5.0 3            #https://pub.dev/packages/google_sign_in
  hive: ^2.0.4                      #https://pub.dev/packages/hive
  hive_flutter: ^1.0.0              #https://pub.dev/packages/hive_flutter
  hive_generator: ^1.1.0            #https://pub.dev/packages/hive_generator/install
  http: ^0.13.3                     #https://pub.dev/packages/http
  json_annotation: ^4.0.0
  json_serializable: ^4.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  synchronized: ^3.0.0              #https://pub.dev/packages/synchronized
  test_api: ^0.4.0
  toggle_switch: ^0.1.9             #https://pub.dev/packages/toggle_switch
  uuid: ^3.0.4
  
dev_dependencies:
  build_runner: ^2.0.3

  flutter_test:
    sdk: flutter
  
  #grinder: ^0.9.0
  #test: ^1.17.4
  
flutter:
  uses-material-design: true

  assets:
    - data/info200.json
    - data/crypto.json
    - assets/images/
    - assets/icons/
