name: web_dashboard
description: A dashboard app sample
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  charts_flutter: ^0.12.0           #https://pub.dev/packages/charts_flutter
  cloud_firestore: ^3.1.17          #https://pub.dev/packages/cloud_firestore
  cupertino_icons: ^1.0.5           #https://pub.dev/packages/cupertino_icons
  dropdown_search: ^5.0.2           #https://pub.dev/packages/dropdown_search
  
  firebase_auth: ^3.3.19            #https://pub.dev/packages/firebase_auth
  firebase_core: ^1.17.1            #https://pub.dev/packages/firebase_core
  fl_chart: ^0.51.0                 #https://pub.dev/packages/fl_chart
  
  flutter:
    sdk: flutter
  
  flutter_datetime_picker: ^1.5.1   #https://pub.dev/packages/flutter_datetime_picker
  flutter_multi_formatter: ^2.5.7   #https://pub.dev/packages/flutter_multi_formatter
  flutter_svg: ^1.1.0              #https://pub.dev/packages/flutter_svg
  get: ^4.6.5                       #https://pub.dev/packages/get
  get_storage: ^2.0.3               #https://pub.dev/packages/get_storage
  google_fonts: ^3.0.1              #https://pub.dev/packages/google_fonts
  google_sign_in: ^5.3.3            #https://pub.dev/packages/google_sign_in
  hive: ^2.2.2                      #https://pub.dev/packages/hive
  hive_flutter: ^1.1.0              #https://pub.dev/packages/hive_flutter
  hive_generator: ^1.1.3            #https://pub.dev/packages/hive_generator/install
  http: ^0.13.4                     #https://pub.dev/packages/http
  json_annotation: ^4.5.0           #https://pub.dev/packages/json_annotation
  json_serializable: ^6.2.0         #https://pub.dev/packages/json_serializable
  logger: ^1.1.0                    #https://pub.dev/packages/logger
  provider: ^6.0.3                  #https://pub.dev/packages/provider

  settings_ui: ^2.0.2               #https://pub.dev/packages/settings_ui
  synchronized: ^3.0.0              #https://pub.dev/packages/synchronized
  test_api: ^0.4.0
  toggle_switch: ^2.0.1             #https://pub.dev/packages/toggle_switch
  uuid: ^3.0.6                      #https://pub.dev/packages/uuid
  
dev_dependencies:
  build_runner: ^2.0.3

  flutter_test:
    sdk: flutter
  
  #grinder: ^0.9.0
  #test: ^1.17.4
  
flutter:
  uses-material-design: true

  assets:
    - data/info200.json
    - data/crypto.json
    - images/
    - icons/
