name: web_dashboard
description: A dashboard app sample
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  charts_flutter: ^0.10.0
  cloud_firestore: ^2.1.0
  cupertino_icons: ^1.0.3
  dropdown_search: ^0.6.1 #https://pub.dev/packages/dropdown_search
  
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  
  flutter:
    sdk: flutter
  
  flutter_datetime_picker: ^1.5.1 #https://pub.dev/packages/flutter_datetime_picker
  flutter_multi_formatter: ^2.1.0 #https://pub.dev/packages/flutter_multi_formatter
  google_sign_in: ^5.0 3
  http: ^0.13.3 #https://pub.dev/packages/http
  json_annotation: ^4.0.0
  json_serializable: ^4.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  test_api: ^0.3.0
  toggle_switch: ^0.1.9 #https://pub.dev/packages/toggle_switch
  uuid: ^3.0.4
  
dev_dependencies:
  build_runner: ^2.0.3

  flutter_test:
    sdk: flutter
  
  #grinder: ^0.9.0
  #test: ^1.17.4
  
flutter:
  uses-material-design: true

  assets:
    - assets/data/info200.json
    - assets/data/crypto.json
